name: release
run-name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_test_nix:
    name: build flatpak appimage
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ubuntu-24.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: build default package
        run: nix build .
      - name: Build flatpak
        run: nix bundle --bundler github:ralismark/nix-appimage .
      - uses: ncipollo/release-action@v1
        name: release
        with:
          artifacts: topdf.AppImage
